
services:
  # A postgres DB used to store data by the API server microservice.
  voting-app-database:
    image: postgres:14.5
    container_name: voting-app-database
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - voting-app-network

  # The API server microservice.
  # It writes logs directly to the Loki service, exposes metrics for the Prometheus
  # service and sends traces to the Grafana Alloy instance.
  voting-app-server:
    build:
     context: ./voting-App-Server
    container_name: voting-app-server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - voting-app-database
    environment:
      - NAMESPACE=production
      - LOGS_TARGET=http://alloy:3100/loki/api/v1/push
      - TRACING_COLLECTOR_HOST=alloy
      - TRACING_COLLECTOR_PORT=4317
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=ip=1.2.3.5
    networks:
      - voting-app-network

  voting-app-client:
    build:
     context: ./voting-App-Client
    container_name: voting-app-client
    restart: always
    ports:
      - "3001:3001"
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - REACT_APP_URL=/api
    networks:
      - voting-app-network       
  
  nginx:
    image: nginx:alpine
    container_name: voting-app-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - voting-app-client
      - voting-app-server
    networks:
      - voting-app-network

  alloy:
    image: grafana/alloy:v1.10.2
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - "./alloy/config.alloy:/etc/alloy/config.alloy"
      - "./alloy/endpoints.json:/etc/alloy/endpoints.json"
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=public-preview",
      "/etc/alloy/config.alloy",
    ]
    networks:
      - voting-app-network
  
  loki:
    image: grafana/loki:3.5.4
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: ["--pattern-ingester.enabled=true", "-config.file=/etc/loki/local-config.yaml "]
    networks:
      - voting-app-network

  
  mimir:
    image: grafana/mimir:2.17.1
    container_name: mimir
    ports:
      - "9009:9009"
    volumes:
      - ./mimir/mimir-config.yaml:/etc/mimir/mimir-config.yaml
    command:
      [
        "-ingester.native-histograms-ingestion-enabled=true",
        "-config.file=/etc/mimir/mimir-config.yaml",
      ]
    networks:
      - voting-app-network

  
  grafana:
    image: grafana/grafana:12.0.4
    container_name: grafana
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning"
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch traceQLStreaming correlations metricsSummary traceqlEditor traceToMetrics traceToProfiles datatrails
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app,grafana-exploretraces-app
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - voting-app-network
  
  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-5
    container_name: graphite
    ports:
      - "8081:80" 
      - "2003-2004:2003-2004"
      - "8125:8125/udp" 
    environment:
      - GRAPHITE_TIME_ZONE=UTC
    volumes:
      - graphite-data:/opt/graphite/storage
    networks:
      - voting-app-network
  
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: mydb
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "password"
    networks:
      - voting-app-network
   

networks:
  voting-app-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

volumes:
  grafana:
  postgres:
  graphite-data:
  influxdb-data:

